vich_uploader:
    db_driver: orm

    mappings:
        pricer_files:
            uri_prefix: '%pricer_files_dir%'
            upload_destination: '%kernel.project_dir%/%pricer_files_dir%'

        hedging_tool_files:
            uri_prefix: '%hedging_tool_files_dir%'
            upload_destination: '%kernel.project_dir%/public%hedging_tool_files_dir%'
