monolog:
    channels: ['cxl']

    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        syslog_handler:
            type: syslog
            level: error

        cxl:
            level: debug
            type: rotating_file
            path: "%kernel.logs_dir%/cxl.log"
            channels: ["cxl"]
            max_files: 10
